### PR TITLE
Add changelog requirement action for major/minor bumps

### PR DESCRIPTION
**Pull request by emilypgoogle**
"Warn Version Bump" will fail if a PR contains a major/minor bump without a changelog. There most recent test commits show what this failure looks like.

### CODE REVIEW

**Comment by rlazo** [comment]
When running the task locally from inside this branch I get

```
* What went wrong:
Execution failed for task ':common:warnVersionBump'.
> Changes are MAJOR, higher than PATCH. If this is intended, add a changelog entry. Otherwise, revert the changes.
```

Is this expected?

**Comment by emilypgoogle** [comment]
Like the check for API changes task, there needs to be context for what API state to compare against. The action sets up the previous state to be the target branch, the local state may vary.

**Comment by rlazo** [comment]
> Like the check for API changes task, there needs to be context for what API state to compare against. The action sets up the previous state to be the target branch, the local state may vary.

What I'm trying to verify is if the task :

a) correctly identifies the expected version bump
b) needs any additional context to work

My local state is: it's a new repo clone with no local changes. Under these conditions, is the major version warning message expected?

**Comment by emilypgoogle** [comment]
Yes, I believe it's diffing an empty API with the modern API, which will always be major. For local testing, you'd need to run `./gradlew exportApi` for whatever base state you want and then this task would compare against that.

**Comment by rlazo** [comment]
> Yes, I believe it's diffing an empty API with the modern API, which will always be major. For local testing, you'd need to run `./gradlew exportApi` for whatever base state you want and then this task would compare against that.

You're right. Running `./gradlew exportApi` and then `./gradlew warnVersionBump` shows no warning, as expected. Could you make this behaviour more explicit? For example, by printing what it's comparing, or by failing the task if there's no file to compare with.

**Review by rlazo — DISMISSED** [review]

**Review by rlazo — APPROVED** [review]

**Pull request merged**
